'use client';

import { ArrowLeft, ArrowRight, Box, Check, Heart, MapPin, PackageCheck, ShieldCheck, Star, Waves } from 'lucide-react';
import Image from 'next/image';
import type { Product } from '@/lib/domain/types';

export function ProductView({ product, onAdd, onBack, onOpenCart, added }: { product: Product; onAdd: () => void; onBack: () => void; onOpenCart: () => void; added: boolean }) {
  return <main className="content"><button className="button-secondary button-small pressable" type="button" onClick={onBack} style={{ marginTop: 47 }}><ArrowLeft size={13} /> Back to collection</button><section className="product-detail motion-fade"><div className="product-detail-image"><Image src={product.imageUrl} alt={product.name} fill sizes="(max-width: 820px) 100vw, 45vw" unoptimized /></div><div className="product-detail-copy"><span className="eyebrow">{product.category} · {product.materials.join(' + ')}</span><h1 className="display">{product.name}</h1><p className="product-detail-price">${product.priceUsd.toFixed(2)}</p><p className="lede">{product.description}</p><div className="detail-facts"><span><PackageCheck size={15} /> {product.inventory} available</span><span><Box size={15} /> {product.weightKg.toFixed(2)} kg</span><span><Star size={15} /> island favorite</span></div><div className="hero-actions"><button className="button-primary pressable" type="button" onClick={onAdd}>{added ? 'Add another to shared parcel' : 'Add to shared parcel'} <ArrowRight size={15} /></button><button className="button-secondary pressable" type="button" aria-label="Save product"><Heart size={15} /> save</button></div>{added ? <div className="product-added-note" role="status"><span><Check size={15} /> Added to your shared parcel.</span><button className="button-link pressable" type="button" onClick={onOpenCart}>View shared cart <ArrowRight size={14} /></button></div> : null}<div className="detail-note"><ShieldCheck size={16} /><span>Coconut will show you the exact pooled shipping effect before you commit.</span></div></div></section><section className="product-story"><div><span className="tiny-label">The making</span><strong>Made slowly, moved together.</strong></div><p>From a fictional workshop in Rarotonga, this piece is represented in the demo with seeded dimensions so the packing engine can make a real recommendation.</p><span className="tiny-label"><MapPin size={12} style={{ display: 'inline', verticalAlign: '-2px' }} /> {product.sellerId} · demo artisan</span></section><div className="footer-note"><span><Waves size={12} style={{ display: 'inline', verticalAlign: '-2px' }} /> Every object carries its island context</span><span><Check size={12} style={{ display: 'inline', verticalAlign: '-2px' }} /> dimensions included in quote</span></div></main>;
}
